language: go
os: linux

jobs:
  include:
    - go: "1.13.x"
      env: GO111MODULE=on
    - go: "1.14.x"
      env: GO111MODULE=off
    - go: "1.15.x"
      env: GO111MODULE=off

script:
  - ./.travis.govet.sh
  - ./.codecov.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)